services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microgames-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - mongo
    networks:
      - microgames
  nginx:
    image: nginx:alpine
    container_name: microgames-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - microgames

  vite:
    image: node:20
    container_name: microgames-vite
    working_dir: /var/www/
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    networks:
      - microgames

  mongo:
    image: mongo
    container_name: microgames-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DB_DATABASE:-microgames}
    volumes:
      - ./docker/mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - microgames

networks:
  microgames:
    driver: bridge
